import { BASE_URL } from '../constants/api';

// Dữ liệu hardcode cho provinces và cities của Việt Nam (sắp xếp theo alphabet)
const VIETNAM_PROVINCES = [
  { code: '89', name: 'An Giang' },
  { code: '24', name: 'Bắc Giang' },
  { code: '06', name: 'Bắc Kạn' },
  { code: '27', name: 'Bắc Ninh' },
  { code: '52', name: 'Bình Định' },
  { code: '74', name: 'Bình Dương' },
  { code: '70', name: 'Bình Phước' },
  { code: '60', name: 'Bình Thuận' },
  { code: '95', name: 'Bạc Liêu' },
  { code: '83', name: 'Bến Tre' },
  { code: '04', name: 'Cao Bằng' },
  { code: '92', name: 'Cần Thơ' },
  { code: '48', name: 'Đà Nẵng' },
  { code: '66', name: 'Đắk Lắk' },
  { code: '67', name: 'Đắk Nông' },
  { code: '11', name: 'Điện Biên' },
  { code: '87', name: 'Đồng Tháp' },
  { code: '75', name: 'Đồng Nai' },
  { code: '64', name: 'Gia Lai' },
  { code: '02', name: 'Hà Giang' },
  { code: '35', name: 'Hà Nam' },
  { code: '01', name: 'Hà Nội' },
  { code: '42', name: 'Hà Tĩnh' },
  { code: '31', name: 'Hải Phòng' },
  { code: '30', name: 'Hải Dương' },
  { code: '93', name: 'Hậu Giang' },
  { code: '79', name: 'Hồ Chí Minh' },
  { code: '17', name: 'Hòa Bình' },
  { code: '33', name: 'Hưng Yên' },
  { code: '56', name: 'Khánh Hòa' },
  { code: '91', name: 'Kiên Giang' },
  { code: '62', name: 'Kon Tum' },
  { code: '12', name: 'Lai Châu' },
  { code: '68', name: 'Lâm Đồng' },
  { code: '10', name: 'Lào Cai' },
  { code: '80', name: 'Long An' },
  { code: '36', name: 'Nam Định' },
  { code: '40', name: 'Nghệ An' },
  { code: '37', name: 'Ninh Bình' },
  { code: '58', name: 'Ninh Thuận' },
  { code: '25', name: 'Phú Thọ' },
  { code: '54', name: 'Phú Yên' },
  { code: '44', name: 'Quảng Bình' },
  { code: '49', name: 'Quảng Nam' },
  { code: '22', name: 'Quảng Ninh' },
  { code: '51', name: 'Quảng Ngãi' },
  { code: '45', name: 'Quảng Trị' },
  { code: '94', name: 'Sóc Trăng' },
  { code: '14', name: 'Sơn La' },
  { code: '72', name: 'Tây Ninh' },
  { code: '19', name: 'Thái Nguyên' },
  { code: '34', name: 'Thái Bình' },
  { code: '46', name: 'Thừa Thiên Huế' },
  { code: '82', name: 'Tiền Giang' },
  { code: '84', name: 'Trà Vinh' },
  { code: '08', name: 'Tuyên Quang' },
  { code: '86', name: 'Vĩnh Long' },
  { code: '26', name: 'Vĩnh Phúc' },
  { code: '15', name: 'Yên Bái' },
];

// Dữ liệu hardcode cho một số cities chính
const VIETNAM_CITIES = {
  '01': [ // Hà Nội
    { code: '001', name: 'Ba Đình' },
    { code: '002', name: 'Hoàn Kiếm' },
    { code: '003', name: 'Tây Hồ' },
    { code: '004', name: 'Long Biên' },
    { code: '005', name: 'Cầu Giấy' },
    { code: '006', name: 'Đống Đa' },
    { code: '007', name: 'Hai Bà Trưng' },
    { code: '008', name: 'Hoàng Mai' },
    { code: '009', name: 'Thanh Xuân' },
    { code: '016', name: 'Sóc Sơn' },
    { code: '017', name: 'Đông Anh' },
    { code: '018', name: 'Gia Lâm' },
    { code: '019', name: 'Nam Từ Liêm' },
    { code: '020', name: 'Thanh Trì' },
    { code: '021', name: 'Bắc Từ Liêm' },
    { code: '250', name: 'Mê Linh' },
    { code: '268', name: 'Hà Đông' },
    { code: '269', name: 'Sơn Tây' },
    { code: '271', name: 'Ba Vì' },
    { code: '272', name: 'Phúc Thọ' },
    { code: '273', name: 'Đan Phượng' },
    { code: '274', name: 'Hoài Đức' },
    { code: '275', name: 'Quốc Oai' },
    { code: '276', name: 'Thạch Thất' },
    { code: '277', name: 'Chương Mỹ' },
    { code: '278', name: 'Thanh Oai' },
    { code: '279', name: 'Thường Tín' },
    { code: '280', name: 'Phú Xuyên' },
    { code: '281', name: 'Ứng Hòa' },
    { code: '282', name: 'Mỹ Đức' },
  ],
  '02': [ // Hà Giang
    { code: '024', name: 'Thành phố Hà Giang' },
    { code: '026', name: 'Huyện Đồng Văn' },
    { code: '027', name: 'Huyện Mèo Vạc' },
    { code: '028', name: 'Huyện Yên Minh' },
    { code: '029', name: 'Huyện Quản Bạ' },
    { code: '030', name: 'Huyện Vị Xuyên' },
    { code: '031', name: 'Huyện Bắc Mê' },
    { code: '032', name: 'Huyện Hoàng Su Phì' },
    { code: '033', name: 'Huyện Xín Mần' },
    { code: '034', name: 'Huyện Bắc Quang' },
    { code: '035', name: 'Huyện Quang Bình' },
  ],
  '04': [ // Cao Bằng
    { code: '040', name: 'Thành phố Cao Bằng' },
    { code: '042', name: 'Huyện Bảo Lạc' },
    { code: '043', name: 'Huyện Thông Nông' },
    { code: '044', name: 'Huyện Hà Quảng' },
    { code: '045', name: 'Huyện Trà Lĩnh' },
    { code: '046', name: 'Huyện Trùng Khánh' },
    { code: '047', name: 'Huyện Hạ Lang' },
    { code: '048', name: 'Huyện Quảng Uyên' },
    { code: '049', name: 'Huyện Phục Hòa' },
    { code: '050', name: 'Huyện Hòa An' },
    { code: '051', name: 'Huyện Nguyên Bình' },
    { code: '052', name: 'Huyện Thạch An' },
  ],
  '06': [ // Bắc Kạn
    { code: '060', name: 'Thành phố Bắc Kạn' },
    { code: '062', name: 'Huyện Pác Nặm' },
    { code: '063', name: 'Huyện Ba Bể' },
    { code: '064', name: 'Huyện Ngân Sơn' },
    { code: '065', name: 'Huyện Bạch Thông' },
    { code: '066', name: 'Huyện Chợ Đồn' },
    { code: '067', name: 'Huyện Chợ Mới' },
    { code: '068', name: 'Huyện Na Rì' },
  ],
  '08': [ // Tuyên Quang
    { code: '070', name: 'Thành phố Tuyên Quang' },
    { code: '071', name: 'Huyện Lâm Bình' },
    { code: '072', name: 'Huyện Na Hang' },
    { code: '073', name: 'Huyện Chiêm Hóa' },
    { code: '074', name: 'Huyện Hàm Yên' },
    { code: '075', name: 'Huyện Yên Sơn' },
    { code: '076', name: 'Huyện Sơn Dương' },
  ],
  '10': [ // Lào Cai
    { code: '080', name: 'Thành phố Lào Cai' },
    { code: '082', name: 'Huyện Bát Xát' },
    { code: '083', name: 'Huyện Mường Khương' },
    { code: '084', name: 'Huyện Si Ma Cai' },
    { code: '085', name: 'Huyện Bắc Hà' },
    { code: '086', name: 'Huyện Bảo Thắng' },
    { code: '087', name: 'Huyện Bảo Yên' },
    { code: '088', name: 'Thị xã Sa Pa' },
    { code: '089', name: 'Huyện Văn Bàn' },
  ],
  '11': [ // Điện Biên
    { code: '094', name: 'Thành phố Điện Biên Phủ' },
    { code: '095', name: 'Thị xã Mường Lay' },
    { code: '096', name: 'Huyện Mường Nhé' },
    { code: '097', name: 'Huyện Mường Chà' },
    { code: '098', name: 'Huyện Tủa Chùa' },
    { code: '099', name: 'Huyện Tuần Giáo' },
    { code: '100', name: 'Huyện Điện Biên' },
    { code: '101', name: 'Huyện Điện Biên Đông' },
    { code: '102', name: 'Huyện Mường Ảng' },
    { code: '103', name: 'Huyện Nậm Pồ' },
  ],
  '12': [ // Lai Châu
    { code: '105', name: 'Thành phố Lai Châu' },
    { code: '106', name: 'Huyện Tam Đường' },
    { code: '107', name: 'Huyện Mường Tè' },
    { code: '108', name: 'Huyện Sìn Hồ' },
    { code: '109', name: 'Huyện Phong Thổ' },
    { code: '110', name: 'Huyện Than Uyên' },
    { code: '111', name: 'Huyện Tân Uyên' },
    { code: '112', name: 'Huyện Nậm Nhùn' },
  ],
  '14': [ // Sơn La
    { code: '116', name: 'Thành phố Sơn La' },
    { code: '118', name: 'Huyện Quỳnh Nhai' },
    { code: '119', name: 'Huyện Thuận Châu' },
    { code: '120', name: 'Huyện Mường La' },
    { code: '121', name: 'Huyện Bắc Yên' },
    { code: '122', name: 'Huyện Phù Yên' },
    { code: '123', name: 'Huyện Mộc Châu' },
    { code: '124', name: 'Huyện Yên Châu' },
    { code: '125', name: 'Huyện Mai Sơn' },
    { code: '126', name: 'Huyện Sông Mã' },
    { code: '127', name: 'Huyện Sốp Cộp' },
    { code: '128', name: 'Huyện Vân Hồ' },
  ],
  '15': [ // Yên Bái
    { code: '132', name: 'Thành phố Yên Bái' },
    { code: '133', name: 'Thị xã Nghĩa Lộ' },
    { code: '135', name: 'Huyện Lục Yên' },
    { code: '136', name: 'Huyện Văn Yên' },
    { code: '137', name: 'Huyện Mù Cang Chải' },
    { code: '138', name: 'Huyện Trấn Yên' },
    { code: '139', name: 'Huyện Trạm Tấu' },
    { code: '140', name: 'Huyện Văn Chấn' },
    { code: '141', name: 'Huyện Yên Bình' },
  ],
  '17': [ // Hòa Bình
    { code: '148', name: 'Thành phố Hòa Bình' },
    { code: '150', name: 'Huyện Đà Bắc' },
    { code: '151', name: 'Huyện Kỳ Sơn' },
    { code: '152', name: 'Huyện Lương Sơn' },
    { code: '153', name: 'Huyện Kim Bôi' },
    { code: '154', name: 'Huyện Cao Phong' },
    { code: '155', name: 'Huyện Tân Lạc' },
    { code: '156', name: 'Huyện Mai Châu' },
    { code: '157', name: 'Huyện Lạc Sơn' },
    { code: '158', name: 'Huyện Yên Thủy' },
    { code: '159', name: 'Huyện Lạc Thủy' },
  ],
  '19': [ // Thái Nguyên
    { code: '164', name: 'Thành phố Thái Nguyên' },
    { code: '165', name: 'Thành phố Sông Công' },
    { code: '167', name: 'Huyện Định Hóa' },
    { code: '168', name: 'Huyện Phú Lương' },
    { code: '169', name: 'Huyện Đồng Hỷ' },
    { code: '170', name: 'Huyện Võ Nhai' },
    { code: '171', name: 'Huyện Đại Từ' },
    { code: '172', name: 'Thị xã Phổ Yên' },
    { code: '173', name: 'Huyện Phú Bình' },
  ],
  '20': [ // Lạng Sơn
    { code: '178', name: 'Thành phố Lạng Sơn' },
    { code: '180', name: 'Huyện Tràng Định' },
    { code: '181', name: 'Huyện Bình Gia' },
    { code: '182', name: 'Huyện Văn Lãng' },
    { code: '183', name: 'Huyện Cao Lộc' },
    { code: '184', name: 'Huyện Văn Quan' },
    { code: '185', name: 'Huyện Bắc Sơn' },
    { code: '186', name: 'Huyện Hữu Lũng' },
    { code: '187', name: 'Huyện Chi Lăng' },
    { code: '188', name: 'Huyện Lộc Bình' },
    { code: '189', name: 'Huyện Đình Lập' },
  ],
  '22': [ // Quảng Ninh
    { code: '193', name: 'Thành phố Hạ Long' },
    { code: '194', name: 'Thành phố Móng Cái' },
    { code: '195', name: 'Thành phố Cẩm Phả' },
    { code: '196', name: 'Thành phố Uông Bí' },
    { code: '198', name: 'Huyện Bình Liêu' },
    { code: '199', name: 'Huyện Tiên Yên' },
    { code: '200', name: 'Huyện Đầm Hà' },
    { code: '201', name: 'Huyện Hải Hà' },
    { code: '202', name: 'Huyện Ba Chẽ' },
    { code: '203', name: 'Huyện Vân Đồn' },
    { code: '204', name: 'Thị xã Đông Triều' },
    { code: '205', name: 'Thị xã Quảng Yên' },
    { code: '206', name: 'Huyện Cô Tô' },
  ],
  '24': [ // Bắc Giang
    { code: '213', name: 'Thành phố Bắc Giang' },
    { code: '215', name: 'Huyện Yên Thế' },
    { code: '216', name: 'Huyện Tân Yên' },
    { code: '217', name: 'Huyện Lạng Giang' },
    { code: '218', name: 'Huyện Lục Nam' },
    { code: '219', name: 'Huyện Lục Ngạn' },
    { code: '220', name: 'Huyện Sơn Động' },
    { code: '221', name: 'Huyện Yên Dũng' },
    { code: '222', name: 'Huyện Việt Yên' },
    { code: '223', name: 'Huyện Hiệp Hòa' },
  ],
  '25': [ // Phú Thọ
    { code: '227', name: 'Thành phố Việt Trì' },
    { code: '228', name: 'Thị xã Phú Thọ' },
    { code: '230', name: 'Huyện Đoan Hùng' },
    { code: '231', name: 'Huyện Hạ Hoà' },
    { code: '232', name: 'Huyện Thanh Ba' },
    { code: '233', name: 'Huyện Phù Ninh' },
    { code: '234', name: 'Huyện Yên Lập' },
    { code: '235', name: 'Huyện Cẩm Khê' },
    { code: '236', name: 'Huyện Tam Nông' },
    { code: '237', name: 'Huyện Lâm Thao' },
    { code: '238', name: 'Huyện Thanh Sơn' },
    { code: '239', name: 'Huyện Thanh Thuỷ' },
    { code: '240', name: 'Huyện Tân Sơn' },
  ],
  '26': [ // Vĩnh Phúc
    { code: '243', name: 'Thành phố Vĩnh Yên' },
    { code: '244', name: 'Thành phố Phúc Yên' },
    { code: '246', name: 'Huyện Lập Thạch' },
    { code: '247', name: 'Huyện Tam Dương' },
    { code: '248', name: 'Huyện Tam Đảo' },
    { code: '249', name: 'Huyện Bình Xuyên' },
    { code: '251', name: 'Huyện Yên Lạc' },
    { code: '252', name: 'Huyện Vĩnh Tường' },
    { code: '253', name: 'Huyện Sông Lô' },
  ],
  '27': [ // Bắc Ninh
    { code: '256', name: 'Thành phố Bắc Ninh' },
    { code: '258', name: 'Huyện Yên Phong' },
    { code: '259', name: 'Huyện Quế Võ' },
    { code: '260', name: 'Huyện Tiên Du' },
    { code: '261', name: 'Thị xã Từ Sơn' },
    { code: '262', name: 'Huyện Thuận Thành' },
    { code: '263', name: 'Huyện Gia Bình' },
    { code: '264', name: 'Huyện Lương Tài' },
  ],
  '30': [ // Hải Dương
    { code: '288', name: 'Thành phố Hải Dương' },
    { code: '290', name: 'Thành phố Chí Linh' },
    { code: '291', name: 'Huyện Nam Sách' },
    { code: '292', name: 'Thị xã Kinh Môn' },
    { code: '293', name: 'Huyện Kim Thành' },
    { code: '294', name: 'Huyện Thanh Hà' },
    { code: '295', name: 'Huyện Cẩm Giàng' },
    { code: '296', name: 'Huyện Bình Giang' },
    { code: '297', name: 'Huyện Gia Lộc' },
    { code: '298', name: 'Huyện Tứ Kỳ' },
    { code: '299', name: 'Huyện Ninh Giang' },
    { code: '300', name: 'Huyện Thanh Miện' },
  ],
  '33': [ // Hưng Yên
    { code: '303', name: 'Thành phố Hưng Yên' },
    { code: '304', name: 'Huyện Văn Lâm' },
    { code: '305', name: 'Huyện Văn Giang' },
    { code: '306', name: 'Huyện Yên Mỹ' },
    { code: '307', name: 'Thị xã Mỹ Hào' },
    { code: '308', name: 'Huyện Ân Thi' },
    { code: '309', name: 'Huyện Khoái Châu' },
    { code: '310', name: 'Huyện Kim Động' },
    { code: '311', name: 'Huyện Tiên Lữ' },
    { code: '312', name: 'Huyện Phù Cừ' },
  ],
  '34': [ // Thái Bình
    { code: '314', name: 'Thành phố Thái Bình' },
    { code: '315', name: 'Huyện Quỳnh Phụ' },
    { code: '316', name: 'Huyện Hưng Hà' },
    { code: '317', name: 'Huyện Đông Hưng' },
    { code: '318', name: 'Huyện Thái Thụy' },
    { code: '319', name: 'Huyện Tiền Hải' },
    { code: '320', name: 'Huyện Kiến Xương' },
    { code: '321', name: 'Huyện Vũ Thư' },
  ],
  '35': [ // Hà Nam
    { code: '323', name: 'Thành phố Phủ Lý' },
    { code: '325', name: 'Thị xã Duy Tiên' },
    { code: '326', name: 'Huyện Kim Bảng' },
    { code: '327', name: 'Huyện Thanh Liêm' },
    { code: '328', name: 'Huyện Bình Lục' },
    { code: '329', name: 'Huyện Lý Nhân' },
  ],
  '36': [ // Nam Định
    { code: '331', name: 'Thành phố Nam Định' },
    { code: '332', name: 'Huyện Mỹ Lộc' },
    { code: '333', name: 'Huyện Vụ Bản' },
    { code: '334', name: 'Huyện Ý Yên' },
    { code: '335', name: 'Huyện Nghĩa Hưng' },
    { code: '336', name: 'Huyện Nam Trực' },
    { code: '337', name: 'Huyện Trực Ninh' },
    { code: '338', name: 'Huyện Xuân Trường' },
    { code: '339', name: 'Huyện Giao Thủy' },
    { code: '340', name: 'Huyện Hải Hậu' },
  ],
  '37': [ // Ninh Bình
    { code: '342', name: 'Thành phố Ninh Bình' },
    { code: '343', name: 'Thành phố Tam Điệp' },
    { code: '344', name: 'Huyện Nho Quan' },
    { code: '345', name: 'Huyện Gia Viễn' },
    { code: '346', name: 'Huyện Hoa Lư' },
    { code: '347', name: 'Huyện Yên Khánh' },
    { code: '348', name: 'Huyện Kim Sơn' },
    { code: '349', name: 'Huyện Yên Mô' },
  ],
  '38': [ // Thanh Hóa
    { code: '356', name: 'Thành phố Thanh Hóa' },
    { code: '357', name: 'Thị xã Bỉm Sơn' },
    { code: '358', name: 'Thành phố Sầm Sơn' },
    { code: '359', name: 'Huyện Mường Lát' },
    { code: '360', name: 'Huyện Quan Hóa' },
    { code: '361', name: 'Huyện Bá Thước' },
    { code: '362', name: 'Huyện Quan Sơn' },
    { code: '363', name: 'Huyện Lang Chánh' },
    { code: '364', name: 'Huyện Ngọc Lặc' },
    { code: '365', name: 'Huyện Cẩm Thủy' },
    { code: '366', name: 'Huyện Thạch Thành' },
    { code: '367', name: 'Huyện Hà Trung' },
    { code: '368', name: 'Huyện Vĩnh Lộc' },
    { code: '369', name: 'Huyện Yên Định' },
    { code: '370', name: 'Huyện Thọ Xuân' },
    { code: '371', name: 'Huyện Thường Xuân' },
    { code: '372', name: 'Huyện Triệu Sơn' },
    { code: '373', name: 'Huyện Thiệu Hóa' },
    { code: '374', name: 'Huyện Hoằng Hóa' },
    { code: '375', name: 'Huyện Hậu Lộc' },
    { code: '376', name: 'Huyện Nga Sơn' },
    { code: '377', name: 'Huyện Như Xuân' },
    { code: '378', name: 'Huyện Như Thanh' },
    { code: '379', name: 'Huyện Nông Cống' },
    { code: '380', name: 'Huyện Đông Sơn' },
    { code: '381', name: 'Huyện Quảng Xương' },
    { code: '382', name: 'Thị xã Nghi Sơn' },
  ],
  '40': [ // Nghệ An
    { code: '384', name: 'Thành phố Vinh' },
    { code: '385', name: 'Thị xã Cửa Lò' },
    { code: '386', name: 'Thị xã Thái Hoà' },
    { code: '387', name: 'Huyện Quế Phong' },
    { code: '388', name: 'Huyện Quỳ Châu' },
    { code: '389', name: 'Huyện Kỳ Sơn' },
    { code: '390', name: 'Huyện Tương Dương' },
    { code: '391', name: 'Huyện Nghĩa Đàn' },
    { code: '392', name: 'Huyện Quỳ Hợp' },
    { code: '393', name: 'Huyện Quỳnh Lưu' },
    { code: '394', name: 'Huyện Con Cuông' },
    { code: '395', name: 'Huyện Tân Kỳ' },
    { code: '396', name: 'Huyện Anh Sơn' },
    { code: '397', name: 'Huyện Diễn Châu' },
    { code: '398', name: 'Huyện Yên Thành' },
    { code: '399', name: 'Huyện Đô Lương' },
    { code: '400', name: 'Huyện Thanh Chương' },
    { code: '401', name: 'Huyện Nghi Lộc' },
    { code: '402', name: 'Huyện Nam Đàn' },
    { code: '403', name: 'Huyện Hưng Nguyên' },
    { code: '404', name: 'Thị xã Hoàng Mai' },
  ],
  '42': [ // Hà Tĩnh
    { code: '406', name: 'Thành phố Hà Tĩnh' },
    { code: '407', name: 'Thị xã Hồng Lĩnh' },
    { code: '408', name: 'Huyện Hương Sơn' },
    { code: '409', name: 'Huyện Đức Thọ' },
    { code: '410', name: 'Huyện Vũ Quang' },
    { code: '411', name: 'Huyện Nghi Xuân' },
    { code: '412', name: 'Huyện Can Lộc' },
    { code: '413', name: 'Huyện Hương Khê' },
    { code: '414', name: 'Huyện Thạch Hà' },
    { code: '415', name: 'Huyện Cẩm Xuyên' },
    { code: '416', name: 'Huyện Kỳ Anh' },
    { code: '417', name: 'Huyện Lộc Hà' },
    { code: '418', name: 'Thị xã Kỳ Anh' },
  ],
  '44': [ // Quảng Bình
    { code: '420', name: 'Thành phố Đồng Hới' },
    { code: '421', name: 'Huyện Minh Hóa' },
    { code: '422', name: 'Huyện Tuyên Hóa' },
    { code: '423', name: 'Huyện Quảng Trạch' },
    { code: '424', name: 'Huyện Bố Trạch' },
    { code: '425', name: 'Huyện Quảng Ninh' },
    { code: '426', name: 'Huyện Lệ Thủy' },
    { code: '427', name: 'Thị xã Ba Đồn' },
  ],
  '45': [ // Quảng Trị
    { code: '432', name: 'Thành phố Đông Hà' },
    { code: '433', name: 'Thị xã Quảng Trị' },
    { code: '434', name: 'Huyện Vĩnh Linh' },
    { code: '435', name: 'Huyện Hướng Hóa' },
    { code: '436', name: 'Huyện Gio Linh' },
    { code: '437', name: 'Huyện Đa Krông' },
    { code: '438', name: 'Huyện Cam Lộ' },
    { code: '439', name: 'Huyện Triệu Phong' },
    { code: '440', name: 'Huyện Hải Lăng' },
    { code: '441', name: 'Huyện Cồn Cỏ' },
  ],
  '46': [ // Thừa Thiên Huế
    { code: '442', name: 'Thành phố Huế' },
    { code: '443', name: 'Huyện Phong Điền' },
    { code: '444', name: 'Huyện Quảng Điền' },
    { code: '445', name: 'Huyện Phú Vang' },
    { code: '446', name: 'Thị xã Hương Thủy' },
    { code: '447', name: 'Thị xã Hương Trà' },
    { code: '448', name: 'Huyện A Lưới' },
    { code: '449', name: 'Huyện Phú Lộc' },
    { code: '450', name: 'Huyện Nam Đông' },
  ],
  '79': [ // Hồ Chí Minh
    { code: '760', name: 'Quận 1' },
    { code: '761', name: 'Quận 12' },
    { code: '762', name: 'Quận Thủ Đức' },
    { code: '763', name: 'Quận 9' },
    { code: '764', name: 'Quận Gò Vấp' },
    { code: '765', name: 'Quận Bình Thạnh' },
    { code: '766', name: 'Quận Tân Bình' },
    { code: '767', name: 'Quận Tân Phú' },
    { code: '768', name: 'Quận Phú Nhuận' },
    { code: '769', name: 'Quận 2' },
    { code: '770', name: 'Quận 3' },
    { code: '771', name: 'Quận 10' },
    { code: '772', name: 'Quận 11' },
    { code: '773', name: 'Quận 4' },
    { code: '774', name: 'Quận 5' },
    { code: '775', name: 'Quận 6' },
    { code: '776', name: 'Quận 8' },
    { code: '777', name: 'Quận Bình Tân' },
    { code: '778', name: 'Quận 7' },
    { code: '783', name: 'Huyện Củ Chi' },
    { code: '784', name: 'Huyện Hóc Môn' },
    { code: '785', name: 'Huyện Bình Chánh' },
    { code: '786', name: 'Huyện Nhà Bè' },
    { code: '787', name: 'Huyện Cần Giờ' },
  ],
  '48': [ // Đà Nẵng
    { code: '490', name: 'Quận Liên Chiểu' },
    { code: '491', name: 'Quận Thanh Khê' },
    { code: '492', name: 'Quận Hải Châu' },
    { code: '493', name: 'Quận Sơn Trà' },
    { code: '494', name: 'Quận Ngũ Hành Sơn' },
    { code: '495', name: 'Quận Cẩm Lệ' },
    { code: '497', name: 'Huyện Hòa Vang' },
    { code: '498', name: 'Huyện Hoàng Sa' },
  ],
  '31': [ // Hải Phòng
    { code: '303', name: 'Quận Hồng Bàng' },
    { code: '304', name: 'Quận Ngô Quyền' },
    { code: '305', name: 'Quận Lê Chân' },
    { code: '306', name: 'Quận Hải An' },
    { code: '307', name: 'Quận Kiến An' },
    { code: '308', name: 'Quận Đồ Sơn' },
    { code: '309', name: 'Quận Dương Kinh' },
    { code: '311', name: 'Huyện Thuỷ Nguyên' },
    { code: '312', name: 'Huyện An Dương' },
    { code: '313', name: 'Huyện An Lão' },
    { code: '314', name: 'Huyện Kiến Thuỵ' },
    { code: '315', name: 'Huyện Tiên Lãng' },
    { code: '316', name: 'Huyện Vĩnh Bảo' },
    { code: '317', name: 'Huyện Cát Hải' },
    { code: '318', name: 'Huyện Bạch Long Vĩ' },
  ],
  '52': [ // Bình Định
    { code: '522', name: 'Thành phố Quy Nhơn' },
    { code: '524', name: 'Huyện An Lão' },
    { code: '525', name: 'Huyện Hoài Nhơn' },
    { code: '526', name: 'Huyện Hoài Ân' },
    { code: '527', name: 'Huyện Phù Mỹ' },
    { code: '528', name: 'Huyện Vĩnh Thạnh' },
    { code: '529', name: 'Huyện Tây Sơn' },
    { code: '530', name: 'Huyện Phù Cát' },
    { code: '531', name: 'Thị xã An Nhơn' },
    { code: '532', name: 'Huyện Tuy Phước' },
    { code: '533', name: 'Huyện Vân Canh' },
  ],
  '49': [ // Quảng Nam
    { code: '503', name: 'Thành phố Tam Kỳ' },
    { code: '504', name: 'Thành phố Hội An' },
    { code: '505', name: 'Huyện Tây Giang' },
    { code: '506', name: 'Huyện Đông Giang' },
    { code: '507', name: 'Huyện Đại Lộc' },
    { code: '508', name: 'Thị xã Điện Bàn' },
    { code: '509', name: 'Huyện Duy Xuyên' },
    { code: '510', name: 'Huyện Quế Sơn' },
    { code: '511', name: 'Huyện Nam Giang' },
    { code: '512', name: 'Huyện Phước Sơn' },
    { code: '513', name: 'Huyện Hiệp Đức' },
    { code: '514', name: 'Huyện Thăng Bình' },
    { code: '515', name: 'Huyện Tiên Phước' },
    { code: '516', name: 'Huyện Bắc Trà My' },
    { code: '517', name: 'Huyện Nam Trà My' },
    { code: '518', name: 'Huyện Núi Thành' },
    { code: '519', name: 'Huyện Phú Ninh' },
    { code: '520', name: 'Huyện Nông Sơn' },
  ],
  '51': [ // Quảng Ngãi
    { code: '522', name: 'Thành phố Quảng Ngãi' },
    { code: '524', name: 'Huyện Bình Sơn' },
    { code: '525', name: 'Huyện Trà Bồng' },
    { code: '526', name: 'Huyện Sơn Tịnh' },
    { code: '527', name: 'Huyện Tư Nghĩa' },
    { code: '528', name: 'Huyện Sơn Hà' },
    { code: '529', name: 'Huyện Sơn Tây' },
    { code: '530', name: 'Huyện Minh Long' },
    { code: '531', name: 'Huyện Nghĩa Hành' },
    { code: '532', name: 'Huyện Mộ Đức' },
    { code: '533', name: 'Thị xã Đức Phổ' },
    { code: '534', name: 'Huyện Ba Tơ' },
    { code: '535', name: 'Huyện Lý Sơn' },
  ],
  '54': [ // Phú Yên
    { code: '540', name: 'Thành phố Tuy Hòa' },
    { code: '542', name: 'Thị xã Sông Cầu' },
    { code: '543', name: 'Huyện Đồng Xuân' },
    { code: '544', name: 'Huyện Tuy An' },
    { code: '545', name: 'Huyện Sơn Hòa' },
    { code: '546', name: 'Huyện Sông Hinh' },
    { code: '547', name: 'Huyện Tây Hòa' },
    { code: '548', name: 'Huyện Phú Hòa' },
    { code: '549', name: 'Thị xã Đông Hòa' },
  ],
  '56': [ // Khánh Hòa
    { code: '560', name: 'Thành phố Nha Trang' },
    { code: '561', name: 'Thành phố Cam Ranh' },
    { code: '562', name: 'Huyện Cam Lâm' },
    { code: '563', name: 'Huyện Vạn Ninh' },
    { code: '564', name: 'Thị xã Ninh Hòa' },
    { code: '565', name: 'Huyện Khánh Vĩnh' },
    { code: '566', name: 'Huyện Diên Khánh' },
    { code: '567', name: 'Huyện Khánh Sơn' },
    { code: '568', name: 'Huyện Trường Sa' },
  ],
  '58': [ // Ninh Thuận
    { code: '580', name: 'Thành phố Phan Rang - Tháp Chàm' },
    { code: '582', name: 'Huyện Bác Ái' },
    { code: '583', name: 'Huyện Ninh Sơn' },
    { code: '584', name: 'Huyện Ninh Hải' },
    { code: '585', name: 'Huyện Ninh Phước' },
    { code: '586', name: 'Huyện Thuận Bắc' },
    { code: '587', name: 'Huyện Thuận Nam' },
  ],
  '60': [ // Bình Thuận
    { code: '600', name: 'Thành phố Phan Thiết' },
    { code: '601', name: 'Thị xã La Gi' },
    { code: '602', name: 'Huyện Tuy Phong' },
    { code: '603', name: 'Huyện Bắc Bình' },
    { code: '604', name: 'Huyện Hàm Thuận Bắc' },
    { code: '605', name: 'Huyện Hàm Thuận Nam' },
    { code: '606', name: 'Huyện Tánh Linh' },
    { code: '607', name: 'Huyện Đức Linh' },
    { code: '608', name: 'Huyện Hàm Tân' },
    { code: '609', name: 'Huyện Phú Quý' },
  ],
  '62': [ // Kon Tum
    { code: '620', name: 'Thành phố Kon Tum' },
    { code: '622', name: 'Huyện Đắk Glei' },
    { code: '623', name: 'Huyện Ngọc Hồi' },
    { code: '624', name: 'Huyện Đắk Tô' },
    { code: '625', name: 'Huyện Kon Plông' },
    { code: '626', name: 'Huyện Kon Rẫy' },
    { code: '627', name: 'Huyện Đắk Hà' },
    { code: '628', name: 'Huyện Sa Thầy' },
    { code: '629', name: 'Huyện Tu Mơ Rông' },
    { code: '630', name: 'Huyện Ia H\' Drai' },
  ],
  '64': [ // Gia Lai
    { code: '640', name: 'Thành phố Pleiku' },
    { code: '641', name: 'Thị xã An Khê' },
    { code: '642', name: 'Thị xã Ayun Pa' },
    { code: '643', name: 'Huyện KBang' },
    { code: '644', name: 'Huyện Đăk Đoa' },
    { code: '645', name: 'Huyện Chư Păh' },
    { code: '646', name: 'Huyện Ia Grai' },
    { code: '647', name: 'Huyện Mang Yang' },
    { code: '648', name: 'Huyện Kông Chro' },
    { code: '649', name: 'Huyện Đức Cơ' },
    { code: '650', name: 'Huyện Chư Prông' },
    { code: '651', name: 'Huyện Chư Sê' },
    { code: '652', name: 'Huyện Đăk Pơ' },
    { code: '653', name: 'Huyện Ia Pa' },
    { code: '654', name: 'Huyện Krông Pa' },
    { code: '655', name: 'Huyện Phú Thiện' },
    { code: '656', name: 'Huyện Chư Pưh' },
  ],
  '66': [ // Đắk Lắk
    { code: '660', name: 'Thành phố Buôn Ma Thuột' },
    { code: '661', name: 'Thị xã Buôn Hồ' },
    { code: '662', name: 'Huyện Ea H\'leo' },
    { code: '663', name: 'Huyện Ea Súp' },
    { code: '664', name: 'Huyện Buôn Đôn' },
    { code: '665', name: 'Huyện Cư M\'gar' },
    { code: '666', name: 'Huyện Krông Búk' },
    { code: '667', name: 'Huyện Krông Năng' },
    { code: '668', name: 'Huyện Ea Kar' },
    { code: '669', name: 'Huyện M\'Đrắk' },
    { code: '670', name: 'Huyện Krông Bông' },
    { code: '671', name: 'Huyện Krông Pắc' },
    { code: '672', name: 'Huyện Krông A Na' },
    { code: '673', name: 'Huyện Lắk' },
    { code: '674', name: 'Huyện Cư Kuin' },
  ],
  '67': [ // Đắk Nông
    { code: '675', name: 'Thành phố Gia Nghĩa' },
    { code: '676', name: 'Huyện Đăk Glong' },
    { code: '677', name: 'Huyện Cư Jút' },
    { code: '678', name: 'Huyện Đắk Mil' },
    { code: '679', name: 'Huyện Krông Nô' },
    { code: '680', name: 'Huyện Đắk Song' },
    { code: '681', name: 'Huyện Đắk R\'Lấp' },
    { code: '682', name: 'Huyện Tuy Đức' },
  ],
  '68': [ // Lâm Đồng
    { code: '683', name: 'Thành phố Đà Lạt' },
    { code: '684', name: 'Thành phố Bảo Lộc' },
    { code: '685', name: 'Huyện Đam Rông' },
    { code: '686', name: 'Huyện Lạc Dương' },
    { code: '687', name: 'Huyện Lâm Hà' },
    { code: '688', name: 'Huyện Đơn Dương' },
    { code: '689', name: 'Huyện Đức Trọng' },
    { code: '690', name: 'Huyện Di Linh' },
    { code: '691', name: 'Huyện Bảo Lâm' },
    { code: '692', name: 'Huyện Đạ Huoai' },
    { code: '693', name: 'Huyện Đạ Tẻh' },
    { code: '694', name: 'Huyện Cát Tiên' },
  ],
  '70': [ // Bình Phước
    { code: '695', name: 'Thành phố Đồng Xoài' },
    { code: '696', name: 'Thị xã Phước Long' },
    { code: '697', name: 'Thị xã Bình Long' },
    { code: '698', name: 'Huyện Bù Gia Mập' },
    { code: '699', name: 'Huyện Lộc Ninh' },
    { code: '700', name: 'Huyện Bù Đốp' },
    { code: '701', name: 'Huyện Hớn Quản' },
    { code: '702', name: 'Huyện Đồng Phú' },
    { code: '703', name: 'Huyện Bù Đăng' },
    { code: '704', name: 'Huyện Chơn Thành' },
    { code: '705', name: 'Huyện Phú Riềng' },
  ],
  '72': [ // Tây Ninh
    { code: '706', name: 'Thành phố Tây Ninh' },
    { code: '707', name: 'Huyện Tân Biên' },
    { code: '708', name: 'Huyện Tân Châu' },
    { code: '709', name: 'Huyện Dương Minh Châu' },
    { code: '710', name: 'Huyện Châu Thành' },
    { code: '711', name: 'Thị xã Hòa Thành' },
    { code: '712', name: 'Huyện Gò Dầu' },
    { code: '713', name: 'Huyện Bến Cầu' },
    { code: '714', name: 'Thị xã Trảng Bàng' },
  ],
  '74': [ // Bình Dương
    { code: '715', name: 'Thành phố Thủ Dầu Một' },
    { code: '716', name: 'Huyện Bàu Bàng' },
    { code: '717', name: 'Huyện Dầu Tiếng' },
    { code: '718', name: 'Thị xã Bến Cát' },
    { code: '719', name: 'Huyện Phú Giáo' },
    { code: '720', name: 'Thị xã Tân Uyên' },
    { code: '721', name: 'Thành phố Dĩ An' },
    { code: '722', name: 'Thành phố Thuận An' },
    { code: '723', name: 'Huyện Bắc Tân Uyên' },
  ],
  '75': [ // Đồng Nai
    { code: '724', name: 'Thành phố Biên Hòa' },
    { code: '725', name: 'Thành phố Long Khánh' },
    { code: '726', name: 'Huyện Tân Phú' },
    { code: '727', name: 'Huyện Vĩnh Cửu' },
    { code: '728', name: 'Huyện Định Quán' },
    { code: '729', name: 'Huyện Trảng Bom' },
    { code: '730', name: 'Huyện Thống Nhất' },
    { code: '731', name: 'Huyện Cẩm Mỹ' },
    { code: '732', name: 'Huyện Long Thành' },
    { code: '733', name: 'Huyện Xuân Lộc' },
    { code: '734', name: 'Huyện Nhơn Trạch' },
  ],
  '77': [ // Bà Rịa - Vũng Tàu
    { code: '735', name: 'Thành phố Vũng Tàu' },
    { code: '736', name: 'Thành phố Bà Rịa' },
    { code: '737', name: 'Huyện Châu Đức' },
    { code: '738', name: 'Huyện Xuyên Mộc' },
    { code: '739', name: 'Huyện Long Điền' },
    { code: '740', name: 'Huyện Đất Đỏ' },
    { code: '741', name: 'Thị xã Phú Mỹ' },
    { code: '742', name: 'Huyện Côn Đảo' },
  ],
  '80': [ // Long An
    { code: '743', name: 'Thành phố Tân An' },
    { code: '744', name: 'Thị xã Kiến Tường' },
    { code: '745', name: 'Huyện Tân Hưng' },
    { code: '746', name: 'Huyện Vĩnh Hưng' },
    { code: '747', name: 'Huyện Mộc Hóa' },
    { code: '748', name: 'Huyện Tân Thạnh' },
    { code: '749', name: 'Huyện Thạnh Hóa' },
    { code: '750', name: 'Huyện Đức Huệ' },
    { code: '751', name: 'Huyện Đức Hòa' },
    { code: '752', name: 'Huyện Bến Lức' },
    { code: '753', name: 'Huyện Thủ Thừa' },
    { code: '754', name: 'Huyện Tân Trụ' },
    { code: '755', name: 'Huyện Cần Đước' },
    { code: '756', name: 'Huyện Cần Giuộc' },
    { code: '757', name: 'Huyện Châu Thành' },
  ],
  '82': [ // Tiền Giang
    { code: '758', name: 'Thành phố Mỹ Tho' },
    { code: '759', name: 'Thị xã Gò Công' },
    { code: '760', name: 'Thị xã Cai Lậy' },
    { code: '761', name: 'Huyện Tân Phước' },
    { code: '762', name: 'Huyện Cái Bè' },
    { code: '763', name: 'Huyện Cai Lậy' },
    { code: '764', name: 'Huyện Châu Thành' },
    { code: '765', name: 'Huyện Chợ Gạo' },
    { code: '766', name: 'Huyện Gò Công Tây' },
    { code: '767', name: 'Huyện Gò Công Đông' },
    { code: '768', name: 'Huyện Tân Phú Đông' },
  ],
  '83': [ // Bến Tre
    { code: '769', name: 'Thành phố Bến Tre' },
    { code: '770', name: 'Huyện Châu Thành' },
    { code: '771', name: 'Huyện Chợ Lách' },
    { code: '772', name: 'Huyện Mỏ Cày Nam' },
    { code: '773', name: 'Huyện Giồng Trôm' },
    { code: '774', name: 'Huyện Bình Đại' },
    { code: '775', name: 'Huyện Ba Tri' },
    { code: '776', name: 'Huyện Thạnh Phú' },
    { code: '777', name: 'Huyện Mỏ Cày Bắc' },
  ],
  '84': [ // Trà Vinh
    { code: '778', name: 'Thành phố Trà Vinh' },
    { code: '779', name: 'Huyện Càng Long' },
    { code: '780', name: 'Huyện Cầu Kè' },
    { code: '781', name: 'Huyện Tiểu Cần' },
    { code: '782', name: 'Huyện Châu Thành' },
    { code: '783', name: 'Huyện Cầu Ngang' },
    { code: '784', name: 'Huyện Trà Cú' },
    { code: '785', name: 'Huyện Duyên Hải' },
    { code: '786', name: 'Thị xã Duyên Hải' },
  ],
  '86': [ // Vĩnh Long
    { code: '787', name: 'Thành phố Vĩnh Long' },
    { code: '788', name: 'Huyện Long Hồ' },
    { code: '789', name: 'Huyện Mang Thít' },
    { code: '790', name: 'Huyện Vũng Liêm' },
    { code: '791', name: 'Huyện Tam Bình' },
    { code: '792', name: 'Thị xã Bình Minh' },
    { code: '793', name: 'Huyện Trà Ôn' },
    { code: '794', name: 'Huyện Bình Tân' },
  ],
  '87': [ // Đồng Tháp
    { code: '795', name: 'Thành phố Cao Lãnh' },
    { code: '796', name: 'Thành phố Sa Đéc' },
    { code: '797', name: 'Thành phố Hồng Ngự' },
    { code: '798', name: 'Huyện Tân Hồng' },
    { code: '799', name: 'Huyện Hồng Ngự' },
    { code: '800', name: 'Huyện Tam Nông' },
    { code: '801', name: 'Huyện Tháp Mười' },
    { code: '802', name: 'Huyện Cao Lãnh' },
    { code: '803', name: 'Huyện Thanh Bình' },
    { code: '804', name: 'Huyện Lấp Vò' },
    { code: '805', name: 'Huyện Lai Vung' },
    { code: '806', name: 'Huyện Châu Thành' },
  ],
  '89': [ // An Giang
    { code: '807', name: 'Thành phố Long Xuyên' },
    { code: '808', name: 'Thành phố Châu Đốc' },
    { code: '809', name: 'Huyện An Phú' },
    { code: '810', name: 'Thị xã Tân Châu' },
    { code: '811', name: 'Huyện Phú Tân' },
    { code: '812', name: 'Huyện Châu Phú' },
    { code: '813', name: 'Huyện Tịnh Biên' },
    { code: '814', name: 'Huyện Tri Tôn' },
    { code: '815', name: 'Huyện Châu Thành' },
    { code: '816', name: 'Huyện Chợ Mới' },
    { code: '817', name: 'Huyện Thoại Sơn' },
  ],
  '91': [ // Kiên Giang
    { code: '818', name: 'Thành phố Rạch Giá' },
    { code: '819', name: 'Thành phố Hà Tiên' },
    { code: '820', name: 'Huyện Kiên Lương' },
    { code: '821', name: 'Huyện Hòn Đất' },
    { code: '822', name: 'Huyện Tân Hiệp' },
    { code: '823', name: 'Huyện Châu Thành' },
    { code: '824', name: 'Huyện Giồng Riềng' },
    { code: '825', name: 'Huyện Gò Quao' },
    { code: '826', name: 'Huyện An Biên' },
    { code: '827', name: 'Huyện An Minh' },
    { code: '828', name: 'Huyện Vĩnh Thuận' },
    { code: '829', name: 'Thành phố Phú Quốc' },
    { code: '830', name: 'Huyện Kiên Hải' },
    { code: '831', name: 'Huyện U Minh Thượng' },
    { code: '832', name: 'Huyện Giang Thành' },
  ],
  '93': [ // Hậu Giang
    { code: '833', name: 'Thành phố Vị Thanh' },
    { code: '834', name: 'Thành phố Ngã Bảy' },
    { code: '835', name: 'Huyện Châu Thành A' },
    { code: '836', name: 'Huyện Châu Thành' },
    { code: '837', name: 'Huyện Phụng Hiệp' },
    { code: '838', name: 'Huyện Vị Thủy' },
    { code: '839', name: 'Huyện Long Mỹ' },
    { code: '840', name: 'Thị xã Long Mỹ' },
  ],
  '94': [ // Sóc Trăng
    { code: '841', name: 'Thành phố Sóc Trăng' },
    { code: '842', name: 'Huyện Châu Thành' },
    { code: '843', name: 'Huyện Kế Sách' },
    { code: '844', name: 'Huyện Mỹ Tú' },
    { code: '845', name: 'Huyện Cù Lao Dung' },
    { code: '846', name: 'Huyện Long Phú' },
    { code: '847', name: 'Huyện Mỹ Xuyên' },
    { code: '848', name: 'Thị xã Ngã Năm' },
    { code: '849', name: 'Huyện Thạnh Trị' },
    { code: '850', name: 'Thị xã Vĩnh Châu' },
    { code: '851', name: 'Huyện Trần Đề' },
  ],
  '95': [ // Bạc Liêu
    { code: '852', name: 'Thành phố Bạc Liêu' },
    { code: '853', name: 'Huyện Hồng Dân' },
    { code: '854', name: 'Huyện Phước Long' },
    { code: '855', name: 'Huyện Vĩnh Lợi' },
    { code: '856', name: 'Thị xã Giá Rai' },
    { code: '857', name: 'Huyện Đông Hải' },
    { code: '858', name: 'Huyện Hoà Bình' },
  ],
  '96': [ // Cà Mau
    { code: '859', name: 'Thành phố Cà Mau' },
    { code: '860', name: 'Huyện U Minh' },
    { code: '861', name: 'Huyện Thới Bình' },
    { code: '862', name: 'Huyện Trần Văn Thời' },
    { code: '863', name: 'Huyện Cái Nước' },
    { code: '864', name: 'Huyện Đầm Dơi' },
    { code: '865', name: 'Huyện Năm Căn' },
    { code: '866', name: 'Huyện Phú Tân' },
    { code: '867', name: 'Huyện Ngọc Hiển' },
  ],
};

const locationService = {
  // Lấy danh sách tất cả provinces
  async getProvinces() {
    try {
      // Thử call API trước, nếu fail thì dùng hardcode
      const response = await fetch(`${BASE_URL}/api/location/provinces`);
      if (response.ok) {
        return await response.json();
      }
    } catch (error) {
      console.log('API provinces not available, using hardcoded data');
    }
    
    // Fallback to hardcoded data
    return VIETNAM_PROVINCES;
  },

  // Lấy danh sách districts/cities theo province code
  async getDistricts(provinceCode) {
    try {
      // Thử call API trước, nếu fail thì dùng hardcode
      const response = await fetch(`${BASE_URL}/api/location/districts/${provinceCode}`);
      if (response.ok) {
        return await response.json();
      }
    } catch (error) {
      console.log('API districts not available, using hardcoded data');
    }
    
    // Fallback to hardcoded data
    return VIETNAM_CITIES[provinceCode] || [];
  },

  // Lấy danh sách wards theo district code
  async getWards(districtCode) {
    try {
      // Thử call API trước, nếu fail thì dùng hardcode
      const response = await fetch(`${BASE_URL}/api/location/wards/${districtCode}`);
      if (response.ok) {
        return await response.json();
      }
    } catch (error) {
      console.log('API wards not available, using hardcoded data');
    }
    
    // Fallback to hardcoded data (empty array for now)
    return [];
  }
};

export default locationService; 