// Language list with flags from REST Countries API
export const LANGUAGE_SUGGESTIONS = [
  { name: 'Afrikaans', flag: '🇿🇦' },
  { name: 'Albanian', flag: '🇦🇱' },
  { name: 'Amharic', flag: '🇪🇹' },
  { name: 'Arabic', flag: '🇸🇦' },
  { name: 'Aramaic', flag: '🇸🇾' },
  { name: 'Armenian', flag: '🇦🇲' },
  { name: 'Aymara', flag: '🇧🇴' },
  { name: 'Azerbaijani', flag: '🇦🇿' },
  { name: 'Basque', flag: '🇪🇸' },
  { name: 'Belarusian', flag: '🇧🇾' },
  { name: 'Bengali', flag: '🇧🇩' },
  { name: 'Berber', flag: '🇲🇦' },
  { name: 'Bislama', flag: '🇻🇺' },
  { name: 'Bosnian', flag: '🇧🇦' },
  { name: 'Bulgarian', flag: '🇧🇬' },
  { name: 'Burmese', flag: '🇲🇲' },
  { name: 'Catalan', flag: '🇪🇸' },
  { name: 'Chinese', flag: '🇨🇳' },
  { name: 'Comorian', flag: '🇰🇲' },
  { name: 'Croatian', flag: '🇭🇷' },
  { name: 'Czech', flag: '🇨🇿' },
  { name: 'Danish', flag: '🇩🇰' },
  { name: 'Dutch', flag: '🇳🇱' },
  { name: 'Dzongkha', flag: '🇧🇹' },
  { name: 'English', flag: '🇬🇧' },
  { name: 'Estonian', flag: '🇪🇪' },
  { name: 'Faroese', flag: '🇫🇴' },
  { name: 'Fijian', flag: '🇫🇯' },
  { name: 'Filipino', flag: '🇵🇭' },
  { name: 'Finnish', flag: '🇫🇮' },
  { name: 'French', flag: '🇫🇷' },
  { name: 'Galician', flag: '🇪🇸' },
  { name: 'Georgian', flag: '🇬🇪' },
  { name: 'German', flag: '🇩🇪' },
  { name: 'Greek', flag: '🇬🇷' },
  { name: 'Guaraní', flag: '🇵🇾' },
  { name: 'Haitian Creole', flag: '🇭🇹' },
  { name: 'Hebrew', flag: '🇮🇱' },
  { name: 'Hindi', flag: '🇮🇳' },
  { name: 'Hungarian', flag: '🇭🇺' },
  { name: 'Icelandic', flag: '🇮🇸' },
  { name: 'Indonesian', flag: '🇮🇩' },
  { name: 'Irish', flag: '🇮🇪' },
  { name: 'Italian', flag: '🇮🇹' },
  { name: 'Japanese', flag: '🇯🇵' },
  { name: 'Kazakh', flag: '🇰🇿' },
  { name: 'Khmer', flag: '🇰🇭' },
  { name: 'Korean', flag: '🇰🇷' },
  { name: 'Kyrgyz', flag: '🇰🇬' },
  { name: 'Lao', flag: '🇱🇦' },
  { name: 'Latin', flag: '🇻🇦' },
  { name: 'Latvian', flag: '🇱🇻' },
  { name: 'Lithuanian', flag: '🇱🇹' },
  { name: 'Luxembourgish', flag: '🇱🇺' },
  { name: 'Macedonian', flag: '🇲🇰' },
  { name: 'Malagasy', flag: '🇲🇬' },
  { name: 'Malay', flag: '🇲🇾' },
  { name: 'Malayalam', flag: '🇮🇳' },
  { name: 'Maldivian', flag: '🇲🇻' },
  { name: 'Maltese', flag: '🇲🇹' },
  { name: 'Māori', flag: '🇳🇿' },
  { name: 'Marathi', flag: '🇮🇳' },
  { name: 'Marshallese', flag: '🇲🇭' },
  { name: 'Mongolian', flag: '🇲🇳' },
  { name: 'Montenegrin', flag: '🇲🇪' },
  { name: 'Nauru', flag: '🇳🇷' },
  { name: 'Nepali', flag: '🇳🇵' },
  { name: 'Niuean', flag: '🇳🇺' },
  { name: 'Norwegian', flag: '🇳🇴' },
  { name: 'Norwegian Bokmål', flag: '🇳🇴' },
  { name: 'Norwegian Nynorsk', flag: '🇳🇴' },
  { name: 'Palauan', flag: '🇵🇼' },
  { name: 'Persian (Farsi)', flag: '🇮🇷' },
  { name: 'Polish', flag: '🇵🇱' },
  { name: 'Portuguese', flag: '🇵🇹' },
  { name: 'Quechua', flag: '🇵🇪' },
  { name: 'Romanian', flag: '🇷🇴' },
  { name: 'Romansh', flag: '🇨🇭' },
  { name: 'Russian', flag: '🇷🇺' },
  { name: 'Samoan', flag: '🇼🇸' },
  { name: 'Serbian', flag: '🇷🇸' },
  { name: 'Seychellois Creole', flag: '🇸🇨' },
  { name: 'Sinhala', flag: '🇱🇰' },
  { name: 'Slovak', flag: '🇸🇰' },
  { name: 'Slovene', flag: '🇸🇮' },
  { name: 'Somali', flag: '🇸🇴' },
  { name: 'Spanish', flag: '🇪🇸' },
  { name: 'Swahili', flag: '🇹🇿' },
  { name: 'Swedish', flag: '🇸🇪' },
  { name: 'Swiss German', flag: '🇨🇭' },
  { name: 'Tajik', flag: '🇹🇯' },
  { name: 'Tamil', flag: '🇮🇳' },
  { name: 'Telugu', flag: '🇮🇳' },
  { name: 'Tetum', flag: '🇹🇱' },
  { name: 'Thai', flag: '🇹🇭' },
  { name: 'Tigrinya', flag: '🇪🇷' },
  { name: 'Tok Pisin', flag: '🇵🇬' },
  { name: 'Tongan', flag: '🇹🇴' },
  { name: 'Turkish', flag: '🇹🇷' },
  { name: 'Turkmen', flag: '🇹🇲' },
  { name: 'Ukrainian', flag: '🇺🇦' },
  { name: 'Urdu', flag: '🇵🇰' },
  { name: 'Uzbek', flag: '🇺🇿' },
  { name: 'Vietnamese', flag: '🇻🇳' },
  { name: 'Welsh', flag: '🇬🇧' },
];

// Map language names to flag emojis for easy lookup
export const LANGUAGE_FLAGS = LANGUAGE_SUGGESTIONS.reduce((acc, lang) => {
  acc[lang.name] = lang.flag;
  return acc;
}, {});

// Helper function to get flag by language name
export const getLanguageFlag = (languageName) => {
  return LANGUAGE_FLAGS[languageName] || '🌐'; // Default flag if not found
};

// Helper function to search languages
export const searchLanguages = (searchText) => {
  if (!searchText.trim()) {
    return LANGUAGE_SUGGESTIONS;
  }
  return LANGUAGE_SUGGESTIONS.filter(lang => 
    lang.name.toLowerCase().includes(searchText.toLowerCase())
  );
}; 